name: check

on:
  push:
    branches: main

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        architecture: [ x64, arm64 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Test all modules
        run: ./gradlew check
